name: voicecraft
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - aom=3.8.2=h59595ed_0
  - asttokens=2.4.1=pyhd8ed1ab_0
  - atk-1.0=2.38.0=hd4edc92_1
  - audioread=3.0.1=py39hf3d152e_1
  - backcall=0.2.0=pyh9f0ad1d_0
  - baumwelch=0.3.7=h00ab1b0_5
  - biopython=1.79=py39hb9d737c_3
  - brotli=1.1.0=hd590300_1
  - brotli-bin=1.1.0=hd590300_1
  - brotli-python=1.1.0=py39h3d6467e_1
  - bzip2=1.0.8=hd590300_5
  - ca-certificates=2024.2.2=hbcca054_0
  - cairo=1.18.0=h3faef2a_0
  - certifi=2024.2.2=pyhd8ed1ab_0
  - cffi=1.16.0=py39h7a31438_0
  - charset-normalizer=3.3.2=pyhd8ed1ab_0
  - click=8.1.7=unix_pyh707e725_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - comm=0.2.2=pyhd8ed1ab_0
  - contourpy=1.2.0=py39h7633fee_0
  - cycler=0.12.1=pyhd8ed1ab_0
  - dataclassy=1.0.1=pyhd8ed1ab_0
  - dav1d=1.2.1=hd590300_0
  - debugpy=1.8.1=py39h3d6467e_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - executing=2.0.1=pyhd8ed1ab_0
  - expat=2.6.2=h59595ed_0
  - ffmpeg=6.1.1=gpl_h38e077a_106
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_1
  - fontconfig=2.14.2=h14ed4e7_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.49.0=py39hd1e30aa_0
  - freetype=2.12.1=h267a509_2
  - fribidi=1.0.10=h36c2ea0_0
  - gdk-pixbuf=2.42.10=h829c605_5
  - gettext=0.21.1=h27087fc_0
  - giflib=5.2.1=h0b41bf4_3
  - gmp=6.3.0=h59595ed_1
  - gnutls=3.7.9=hb077bed_0
  - graphite2=1.3.13=h58526e2_1001
  - graphviz=9.0.0=h78e8752_1
  - greenlet=3.0.3=py39h3d6467e_0
  - gtk2=2.24.33=h280cfa0_4
  - gts=0.7.6=h977cf35_4
  - harfbuzz=8.3.0=h3d44ed6_0
  - hdbscan=0.8.33=py39h44dd56e_4
  - icu=73.2=h59595ed_0
  - idna=3.6=pyhd8ed1ab_0
  - importlib-metadata=7.0.2=pyha770c72_0
  - importlib-resources=6.3.0=pyhd8ed1ab_0
  - importlib_metadata=7.0.2=hd8ed1ab_0
  - importlib_resources=6.3.0=pyhd8ed1ab_0
  - ipykernel=6.29.3=pyhd33586a_0
  - jedi=0.19.1=pyhd8ed1ab_0
  - joblib=1.3.2=pyhd8ed1ab_0
  - jupyter_client=8.6.1=pyhd8ed1ab_0
  - jupyter_core=5.7.2=py39hf3d152e_0
  - kaldi=5.5.1068=cpu_h31769b2_2
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.5=py39h7633fee_1
  - kneed=0.8.5=pyhd8ed1ab_0
  - krb5=1.21.2=h659d440_0
  - lame=3.100=h166bdaf_1003
  - lazy_loader=0.3=pyhd8ed1ab_0
  - lcms2=2.16=hb7c19ff_0
  - ld_impl_linux-64=2.40=h41732ed_0
  - lerc=4.0.0=h27087fc_0
  - libabseil=20240116.1=cxx17_h59595ed_2
  - libass=0.17.1=h8fe9dca_1
  - libblas=3.9.0=21_linux64_openblas
  - libbrotlicommon=1.1.0=hd590300_1
  - libbrotlidec=1.1.0=hd590300_1
  - libbrotlienc=1.1.0=hd590300_1
  - libcblas=3.9.0=21_linux64_openblas
  - libclang-cpp15=15.0.7=default_hb11cfb5_4
  - libdeflate=1.19=hd590300_0
  - libdrm=2.4.120=hd590300_0
  - libedit=3.1.20191231=he28a2e2_2
  - libexpat=2.6.2=h59595ed_0
  - libffi=3.4.2=h7f98852_5
  - libflac=1.4.3=h59595ed_0
  - libgcc-ng=13.2.0=h807b86a_5
  - libgd=2.3.3=h119a65a_9
  - libgfortran-ng=13.2.0=h69a702a_5
  - libgfortran5=13.2.0=ha4646dd_5
  - libglib=2.80.0=hf2295e7_0
  - libgomp=13.2.0=h807b86a_5
  - libhwloc=2.9.3=default_h554bfaf_1009
  - libiconv=1.17=hd590300_2
  - libidn2=2.3.7=hd590300_0
  - libjpeg-turbo=3.0.0=hd590300_1
  - liblapack=3.9.0=21_linux64_openblas
  - liblapacke=3.9.0=21_linux64_openblas
  - libllvm14=14.0.6=hcd5def8_4
  - libllvm15=15.0.7=hb3ce162_4
  - libllvmspirv15=15.0.0=h0cdce71_1
  - libnsl=2.0.1=hd590300_0
  - libogg=1.3.4=h7f98852_1
  - libopenblas=0.3.26=pthreads_h413a1c8_0
  - libopenvino=2024.0.0=h2e90f83_1
  - libopenvino-auto-batch-plugin=2024.0.0=hd5fc58b_1
  - libopenvino-auto-plugin=2024.0.0=hd5fc58b_1
  - libopenvino-hetero-plugin=2024.0.0=h3ecfda7_1
  - libopenvino-intel-cpu-plugin=2024.0.0=h2e90f83_1
  - libopenvino-intel-gpu-plugin=2024.0.0=h2e90f83_1
  - libopenvino-ir-frontend=2024.0.0=h3ecfda7_1
  - libopenvino-onnx-frontend=2024.0.0=h757c851_1
  - libopenvino-paddle-frontend=2024.0.0=h757c851_1
  - libopenvino-pytorch-frontend=2024.0.0=h59595ed_1
  - libopenvino-tensorflow-frontend=2024.0.0=hca94c1a_1
  - libopenvino-tensorflow-lite-frontend=2024.0.0=h59595ed_1
  - libopus=1.3.1=h7f98852_1
  - libpciaccess=0.18=hd590300_0
  - libpng=1.6.43=h2797004_0
  - libpq=16.2=h33b98f1_0
  - libprotobuf=4.25.3=h08a7969_0
  - librosa=0.10.1=pyhd8ed1ab_0
  - librsvg=2.56.3=he3f83f7_1
  - libsndfile=1.2.2=hc60ed4a_1
  - libsodium=1.0.18=h36c2ea0_1
  - libsqlite=3.45.2=h2797004_0
  - libstdcxx-ng=13.2.0=h7e041cc_5
  - libtasn1=4.19.0=h166bdaf_0
  - libtiff=4.6.0=ha9c0a0a_2
  - libunistring=0.9.10=h7f98852_0
  - libuuid=2.38.1=h0b41bf4_0
  - libva=2.21.0=hd590300_0
  - libvorbis=1.3.7=h9c3ff4c_0
  - libvpx=1.14.0=h59595ed_0
  - libwebp=1.3.2=h658648e_1
  - libwebp-base=1.3.2=hd590300_0
  - libxcb=1.15=h0b41bf4_0
  - libxcrypt=4.4.36=hd590300_1
  - libxml2=2.12.5=h232c23b_0
  - libzlib=1.2.13=hd590300_5
  - llvm-spirv-15=15.0.0=h0cdce71_1
  - mad=0.15.1b=h9c3ff4c_1
  - markdown-it-py=3.0.0=pyhd8ed1ab_0
  - matplotlib-base=3.8.3=py39he9076e7_0
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - mdurl=0.1.2=pyhd8ed1ab_0
  - montreal-forced-aligner=2.2.17=pyhd8ed1ab_0
  - mpg123=1.32.4=h59595ed_0
  - msgpack-python=1.0.7=py39h7633fee_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - ncurses=6.4=h59595ed_2
  - nest-asyncio=1.6.0=pyhd8ed1ab_0
  - nettle=3.9.1=h7ab15ed_0
  - ngram=1.3.14=h924138e_2
  - numba=0.59.0=py39h615d6bd_1
  - numpy=1.26.4=py39h474f0d3_0
  - ocl-icd=2.3.2=hd590300_0
  - openfst=1.8.2=h924138e_2
  - openh264=2.4.1=h59595ed_0
  - openjpeg=2.5.2=h488ebb8_0
  - openssl=3.2.1=hd590300_0
  - p11-kit=0.24.1=hc5aa10d_0
  - packaging=24.0=pyhd8ed1ab_0
  - pandas=2.2.1=py39hddac248_0
  - pango=1.52.1=ha41ecd1_0
  - parso=0.8.3=pyhd8ed1ab_0
  - patsy=0.5.6=pyhd8ed1ab_0
  - pcre2=10.43=hcad00b1_0
  - pexpect=4.9.0=pyhd8ed1ab_0
  - pgvector-python=0.2.5=pyhe093146_0
  - pickleshare=0.7.5=py_1003
  - pillow=10.2.0=py39had0adad_0
  - pip=24.0=pyhd8ed1ab_0
  - pixman=0.43.2=h59595ed_0
  - platformdirs=4.2.0=pyhd8ed1ab_0
  - pocl=5.0=h03a6ac1_2
  - pocl-core=5.0=hdaecddf_2
  - pocl-cpu=5.0=he901f76_2
  - pocl-cpu-minimal=5.0=h5ccd973_2
  - pocl-cuda=5.0=hdaecddf_2
  - pocl-remote=5.0=h5ccd973_2
  - pooch=1.8.1=pyhd8ed1ab_0
  - postgresql=16.2=h7387d8b_0
  - prompt-toolkit=3.0.42=pyha770c72_0
  - prompt_toolkit=3.0.42=hd8ed1ab_0
  - psutil=5.9.8=py39hd1e30aa_0
  - psycopg2=2.9.9=py39h89197e3_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pugixml=1.14=h59595ed_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pygments=2.17.2=pyhd8ed1ab_0
  - pyparsing=3.1.2=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha2e5f31_6
  - pysoundfile=0.12.1=pypyhd8ed1ab_1
  - python=3.9.18=h0755675_1_cpython
  - python-tzdata=2024.1=pyhd8ed1ab_0
  - python_abi=3.9=4_cp39
  - pytz=2024.1=pyhd8ed1ab_0
  - pyyaml=6.0.1=py39hd1e30aa_1
  - pyzmq=25.1.2=py39h8c080ef_0
  - readline=8.2=h8228510_1
  - requests=2.31.0=pyhd8ed1ab_0
  - rich=13.7.1=pyhd8ed1ab_0
  - rich-click=1.7.4=pyhd8ed1ab_0
  - scikit-learn=1.2.2=py39hc236052_2
  - scipy=1.12.0=py39h474f0d3_2
  - seaborn=0.13.2=hd8ed1ab_0
  - seaborn-base=0.13.2=pyhd8ed1ab_0
  - setuptools=69.2.0=pyhd8ed1ab_0
  - six=1.16.0=pyh6c4a22f_0
  - snappy=1.1.10=h9fff704_0
  - sox=14.4.2=ha5cc309_1018
  - soxr=0.1.3=h0b41bf4_3
  - soxr-python=0.3.7=py39h44dd56e_0
  - sqlalchemy=2.0.28=py39hd1e30aa_0
  - sqlite=3.45.2=h2c6b66d_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - statsmodels=0.14.1=py39h44dd56e_0
  - svt-av1=1.8.0=h59595ed_0
  - tbb=2021.11.0=h00ab1b0_1
  - threadpoolctl=3.3.0=pyhc1e730c_0
  - tk=8.6.13=noxft_h4845f30_101
  - tornado=6.4=py39hd1e30aa_0
  - tqdm=4.66.2=pyhd8ed1ab_0
  - traitlets=5.14.2=pyhd8ed1ab_0
  - typing-extensions=4.10.0=hd8ed1ab_0
  - typing_extensions=4.10.0=pyha770c72_0
  - tzcode=2024a=h3f72095_0
  - tzdata=2024a=h0c530f3_0
  - unicodedata2=15.1.0=py39hd1e30aa_0
  - urllib3=2.2.1=pyhd8ed1ab_0
  - wcwidth=0.2.13=pyhd8ed1ab_0
  - wheel=0.42.0=pyhd8ed1ab_0
  - x264=1!164.3095=h166bdaf_2
  - x265=3.5=h924138e_3
  - xorg-fixesproto=5.0=h7f98852_1002
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.1.1=hd590300_0
  - xorg-libsm=1.2.4=h7391055_0
  - xorg-libx11=1.8.7=h8ee46fc_0
  - xorg-libxau=1.0.11=hd590300_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h0b41bf4_2
  - xorg-libxfixes=5.0.3=h7f98852_1004
  - xorg-libxrender=0.9.11=hd590300_0
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h0b41bf4_1003
  - xorg-xproto=7.0.31=h7f98852_1007
  - xz=5.2.6=h166bdaf_0
  - yaml=0.2.5=h7f98852_2
  - zeromq=4.3.5=h59595ed_1
  - zipp=3.17.0=pyhd8ed1ab_0
  - zlib=1.2.13=hd590300_5
  - zstd=1.5.5=hfc55251_0
  - pip:
      - absl-py==2.1.0
      - aiofiles==23.2.1
      - aiohttp==3.9.3
      - aiosignal==1.3.1
      - altair==5.2.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.3.0
      - async-timeout==4.0.3
      - attrs==23.2.0
      - av==11.0.0
      - babel==2.14.0
      - beautifulsoup4==4.12.3
      - bibtexparser==2.0.0b7
      - bleach==6.1.0
      - blis==0.7.11
      - catalogue==2.0.10
      - clldutils==3.22.2
      - cloudpickle==3.0.0
      - cmake==3.28.3
      - colorlog==6.8.2
      - confection==0.1.4
      - csvw==3.3.0
      - cymem==2.0.8
      - cython==0.29.37
      - datasets==2.16.0
      - defusedxml==0.7.1
      - demucs==4.0.1
      - dill==0.3.6
      - dlinfo==1.2.1
      - docopt==0.6.2
      - dora-search==0.1.12
      - einops==0.7.0
      - encodec==0.1.1
      - exceptiongroup==1.2.0
      - fastapi==0.110.0
      - fastjsonschema==2.19.1
      - ffmpy==0.3.2
      - filelock==3.13.1
      - flashy==0.0.2
      - frozenlist==1.4.1
      - fsspec==2023.10.0
      - gradio==3.50.2
      - gradio-client==0.6.1
      - grpcio==1.62.1
      - h11==0.14.0
      - httpcore==1.0.4
      - httpx==0.27.0
      - huggingface-hub==0.21.4
      - hydra-colorlog==1.2.0
      - hydra-core==1.3.2
      - ipython==8.12.3
      - isodate==0.6.1
      - jinja2==3.1.3
      - jsonschema==4.21.1
      - jsonschema-specifications==2023.12.1
      - julius==0.2.7
      - jupyterlab-pygments==0.3.0
      - lameenc==1.7.0
      - langcodes==3.3.0
      - language-tags==1.2.0
      - lit==18.1.1
      - llvmlite==0.42.0
      - lxml==5.1.0
      - markdown==3.5.2
      - markupsafe==2.1.5
      - mistune==3.0.2
      - mpmath==1.3.0
      - msgpack==1.0.8
      - multidict==6.0.5
      - multiprocess==0.70.14
      - murmurhash==1.0.10
      - nbclient==0.10.0
      - nbconvert==7.16.3
      - nbformat==5.10.3
      - networkx==3.2.1
      - num2words==0.5.13
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cuda-cupti-cu11==11.7.101
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cudnn-cu11==8.5.0.96
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-curand-cu11==10.2.10.91
      - nvidia-cusolver-cu11==11.4.0.1
      - nvidia-cusparse-cu11==11.7.4.91
      - nvidia-nccl-cu11==2.14.3
      - nvidia-nvtx-cu11==11.7.91
      - omegaconf==2.3.0
      - openunmix==1.2.1
      - orjson==3.9.15
      - pandocfilters==1.5.1
      - pathlib-abc==0.1.1
      - pathy==0.11.0
      - pgvector==0.2.2
      - phonemizer==3.2.1
      - pipreqs==0.5.0
      - praatio==6.2.0
      - preshed==3.0.9
      - protobuf==4.25.3
      - pyarrow==15.0.2
      - pyarrow-hotfix==0.6
      - pydantic==1.10.14
      - pydub==0.25.1
      - pylatexenc==2.10
      - pynini==2.1.6
      - pypinyin==0.48.0
      - python-dateutil==2.9.0.post0
      - python-multipart==0.0.9
      - rdflib==7.0.0
      - referencing==0.33.0
      - regex==2023.12.25
      - responses==0.18.0
      - retrying==1.3.4
      - rfc3986==1.5.0
      - rpds-py==0.18.0
      - safetensors==0.4.2
      - segments==2.2.1
      - semantic-version==2.10.0
      - sentencepiece==0.2.0
      - smart-open==6.4.0
      - sniffio==1.3.1
      - soupsieve==2.5
      - spacy==3.5.2
      - spacy-legacy==3.0.12
      - spacy-loggers==1.0.5
      - srsly==2.4.8
      - starlette==0.36.3
      - submitit==1.5.1
      - sympy==1.12
      - tabulate==0.9.0
      - tensorboard==2.16.2
      - tensorboard-data-server==0.7.2
      - thinc==8.1.12
      - tinycss2==1.2.1
      - tokenizers==0.15.2
      - toolz==0.12.1
      - torch==2.0.1
      - torchaudio==2.0.2
      - torchmetrics==0.11.1
      - transformers==4.38.2
      - treetable==0.2.5
      - triton==2.0.0
      - typer==0.7.0
      - uritemplate==4.1.1
      - uvicorn==0.28.0
      - wasabi==1.1.2
      - webencodings==0.5.1
      - websockets==11.0.3
      - werkzeug==3.0.1
      - xformers==0.0.22
      - xxhash==3.4.1
      - yarg==0.1.9
      - yarl==1.9.4
prefix: /home/pyp/miniconda3/envs/voicecraft
